
-- 4 개의 게시판 중에서 게시판 하나를 선택했을 때
-- 게시판 하나에 올린 글 전체 목록 조회하기
SELECT C.CONTENT_IDX, C.CONTENT_SUBJECT, U.USER_NAME CONTENT_WRITER_NAME, 
      TO_CHAR(C.CONTENT_DATE, 'YYYY-MM-DD')CONTENT_DATE
      FROM CONTENT_TABLE C, USER_TABLE U
      WHERE C.CONTENT_WRITER_IDX = U.USER_IDX
      AND C.CONTENT_BOARD_IDX=4
      ORDER BY C.CONTENT_IDX DESC;
    
-- 게시판 하나에 올린 글 전체 목록에서 
-- 게시글 하나의 제목을 클릭했을 때
-- 해당 게시글 정보만 조회하기
-- 글쓴이 이름, 게시날짜, 제목, 내용, 첨부파일
SELECT U.USER_NAME CONTENT_WRITER_NAME, TO_CHAR(C.CONTENT_DATE, 'YYYY-MM-DD')CONTENT_DATE,
       C.CONTENT_SUBJECT, C.CONTENT_TEXT, C.CONTENT_FILE
      FROM CONTENT_TABLE C, USER_TABLE U
      WHERE C.CONTENT_WRITER_IDX = U.USER_IDX
      AND C.CONTENT_IDX=4;      
      
/*
SELECT U.USER_NAME CONTENT_WRITER_NAME, TO_CHAR(C.CONTENT_DATE, 'YYYY-MM-DD')CONTENT_DATE,
       C.CONTENT_SUBJECT, C.CONTENT_TEXT, C.CONTENT_FILE
      FROM CONTENT_TABLE C, USER_TABLE U
      WHERE C.CONTENT_WRITER_IDX = U.USER_IDX
      AND C.CONTENT_IDX=#{content_idx}
*/
      

DESC CONTENT_TABLE;
DESC USER_TABLE;
      
SELECT CONTENT_SEQ.NEXTVAL FROM DUAL;


-- 게시글 삭제하기
SELECT * FROM CONTENT_TABLE
ORDER BY CONTENT_IDX DESC;

DELETE FROM CONTENT_TABLE;

SELECT * FROM CONTENT_TABLE
ORDER BY CONTENT_IDX DESC;

ROLLBACK;

SELECT * FROM CONTENT_TABLE
ORDER BY CONTENT_IDX DESC;

DELETE FROM CONTENT_TABLE
 WHERE CONTENT_IDX=0;

SELECT * FROM CONTENT_TABLE
ORDER BY CONTENT_IDX DESC;

ROLLBACK;

/*
DELETE FROM CONTENT_TABLE
 WHERE CONTENT_IDX=#{content_idx}
*/

SELECT * FROM USER_TABLE;





      
      